#!/bin/bash
#PBS -N MACE
#PBS -l select=1:ncpus=16:ompthreads=16:ngpus=1:mem=220gb
#PBS -l walltime=24:00:00
#PBS -P 11001786
#PBS -q normal

source activate mace
module load cuda/12.2.2
export OMP_NUM_THREADS=16
module load intel/2025.1.3
module load lapack/3.11-intel
export PATH=/home/users/nus/zhongpc/scratch/zzh/airss-0.9.1/bin:$PATH
export PATH=/home/users/nus/zhongpc/scratch/zzh/vaspkit.1.5.1/bin:${PATH}

cd $PBS_O_WORKDIR

python mace_opt_ph.py  > MACE.LOG
